#!/usr/bin/env python3
"""Assembles the static site (GitHub Pages) into an output folder.

Produced content:
  - a copy of site/;
  - config.js in "static" mode (current season, README link, visit statistics);
  - data/missions.json, built from data/days/*.json.

Usage: build_static.py [--season s6] [--days data/days] [--site site] [--output dist]
The season forced as current comes from the DRG_CURRENT_SEASON environment variable. Without it, the
site deduces the current season from the data (the most recent season of the recent missions).
The "About" link points to the README of the repository being built (GITHUB_REPOSITORY, set by GitHub
Actions), or to --readme-url. Visit statistics are enabled by a GoatCounter site code (DRG_GOATCOUNTER).
"""
import argparse
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


def read_missions(days_folder):
    missions = []
    for file in sorted(Path(days_folder).glob("*.json")):
        missions.extend(json.loads(file.read_text(encoding="utf-8")))
    missions.sort(key=lambda m: (m["start"], m["biome"]))  # stable sort: the file order breaks ties
    return missions


def default_readme_url():
    repository = os.environ.get("GITHUB_REPOSITORY", "")  # "owner/name" inside GitHub Actions
    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    return f"{server}/{repository}#readme" if repository else ""


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--season", default=os.environ.get("DRG_CURRENT_SEASON", ""))
    parser.add_argument("--days", default="data/days")
    parser.add_argument("--site", default="site")
    parser.add_argument("--output", default="dist")
    parser.add_argument("--readme-url", default=default_readme_url())
    parser.add_argument("--goatcounter", default=os.environ.get("DRG_GOATCOUNTER", ""))
    args = parser.parse_args(argv)

    if args.season and not re.fullmatch(r"s\d+", args.season):
        sys.exit(f"Invalid season: {args.season!r} (expected: s followed by a number, e.g. s6)")
    if args.goatcounter and not re.fullmatch(r"[a-z0-9-]+", args.goatcounter):
        sys.exit(f"Invalid GoatCounter code: {args.goatcounter!r} (expected the code of yourcode.goatcounter.com)")
    if args.readme_url and not args.readme_url.startswith("https://"):
        sys.exit(f"Invalid README address: {args.readme_url!r} (expected https://...)")

    output = Path(args.output)
    if output.exists():
        shutil.rmtree(output)
    shutil.copytree(args.site, output)

    config = {"mode": "static", "currentSeason": args.season, "readmeUrl": args.readme_url,
              "goatcounter": args.goatcounter}
    (output / "config.js").write_text(
        "// Generated by tools/build_static.py: GitHub Pages mode.\n"
        f"window.DRG_CONFIG = {json.dumps(config)};\n",
        encoding="utf-8",
    )

    missions = read_missions(args.days)
    if not missions:
        sys.exit(f"No mission found in {args.days}: run collect_static.py first")
    (output / "data").mkdir()
    content = {"generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), "missions": missions}
    (output / "data" / "missions.json").write_text(
        json.dumps(content, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")

    # A web server must be able to read everything, whatever the permissions of the source files.
    for path in [output, *output.rglob("*")]:
        path.chmod(0o755 if path.is_dir() else 0o644)

    season = args.season or "deduced from the data"
    print(f"{len(missions)} missions, from {missions[0]['start']} to {missions[-1]['start']}, season {season} -> {output}/")


if __name__ == "__main__":
    main()
